### ISSUE TITLE
Vanishing Frame rendering issue

### ISSUE THREAD

**Issue by Jukari** [Ordinastie/MalisisBlocks#1]
After some testing, I noticed that when a vanishing frame block has another block placed on it, and it does the flicker effect, it breaks rendering for a lot of the Chisel 2 blocks.  I'm not sure if this is a Chisel 2 issue or a Vanishing frame issue, but after I took down the vanishing frames, I no longer have any block rendering issues.  The Chisel 2 blocks would become all the same and some would be transparent, when in your inventory.  The ones placed in the world seemed to continue looking correct.

**Comment by Ordinastie** [comment]
To be sure I understand, you're saying the while a Vanishing block is flickering/shaking, the chisel blocks inside the inventory are rendered broken ?

**Comment by Jukari** [comment]
Once they flicker the block rendering in your inventory for blocks like the bookshelf, waterstone, and a few other types break until you take down the vanishing frames.

**Comment by Ordinastie** [comment]
To be sure, you're talking in 1.10.2, right ? Can you give me a link to the mod too, please?

**Comment by Jukari** [comment]
Yes, using [MalisisBlocks-1.10.2-4.1.2](https://minecraft.curseforge.com/projects/malisisblocks/files/2337878), and [MalisisCore-1.10.2-4.2.7](https://minecraft.curseforge.com/projects/malisiscore/files/2338043), and using [Chisel 1.10.2-0.0.7.3](https://minecraft.curseforge.com/projects/chisel/files/2339874), and the default resource pack.

**Comment by Ordinastie** [comment]
Fixed in 1.10.2-4.1.3.
