### ISSUE TITLE
Player sensor rendering

### ISSUE THREAD

**Issue by ghost** [Ordinastie/MalisisBlocks#11]
When a player sensor is placed on any block, and another block is placed right next to it, the respective side turns transparent.

![image](https://user-images.githubusercontent.com/17183816/53608938-afab1680-3b92-11e9-97c1-8f153e680c4f.png)

**Comment by xxkromexx** [comment]
Turn off Render Regions on OptiFine.

**Comment by ghost** [comment]
This is over two years old, please have some etiquette.

Disregarding that, I don't use optifine in packs I make for these kinds of reasons, so it's not that.

Closing this to prevent further wasted time.
