### ISSUE TITLE
Hi-Tech Door can be seen through mixed block

### ISSUE THREAD

**Issue by RFShahrear** [Ordinastie/MalisisBlocks#3]
![2017-06-20_09 35 56](https://user-images.githubusercontent.com/29401003/27315616-6696a99c-559c-11e7-9455-321e0560f3ca.png)

using MalisisBlock 4.2.0, MalisisCore 4.4.0 and MalisisDoor 5.2.0.

**Comment by Ordinastie** [comment]
Unfortunately, I don't see a way to fix this.
